dist: trusty

language: python

python:
 - 2.7
 - 3.5
 - 3.6

sudo: false

addons:
  apt:
    packages:
    - rtmpdump
    - python-crypto
    - php5-cli
    - php5-curl

env:
  global:
    - ENABLE_FINLAND_TESTS=0

install:
 # Install from wheel instead of from source in setup.py to speed up CI
 - pip install lxml

 - pip install pyflakes pep8
 - python setup.py install

script:
 - pyflakes yledl/*.py
 - python setup.py pytest
 - yle-dl --help

after_script:
 - pep8 --statistics --count yledl/*.py
